### ISSUE TITLE
Update year display on index

### ISSUE THREAD

**Issue by MattiWe** [tira-io/tira#214]
Currently:
(1) The year displayed on index.html is part of the Organization in the model. It shows a range of years in which the organization was active. This is unintuitive since the year is displayed as part of the task. 
(2) The date is stored as a string, sometimes as range (2017-2020) and sometimes as single year. This can't be sorted. I don't really see a reason to sort by 'earliest activity' and 'active in year' is a more complicated feature which i don't think we need yet.

Relevant dates are: Dates the task was run with hard deadlines (for live tasks) or dates on which a dataset was added. I favor to only display the last date, so I suggest the following changes:

Expected:
The table on index.html only displays the month and year of the newest dataset of the task. It makes sense to add a 'Date' field to the Dataset table in the database (needs not to be stored in the prototext files, since the creation date is encoded in the dataset_id).

**Comment by theelstner** [comment]
Done: changed the order: year(s) appears now as the column after task and before organization.
Minor change to "Expected": 
- Did only change "year" to "year(s)" instead of "from" and "to" column names, because we want to assure that a task can be discontinued for one year and then run in the next again (e.g. 2019-2021,2023). the from-to scheme would not represent this as well as "years"

Before (real tira):
<img width="929" alt="Bildschirmfoto 2022-05-02 um 16 27 50" src="https://user-images.githubusercontent.com/12912413/166251883-c16678a2-e595-44a3-86c4-cf7218a77590.png">


After (toy model tira):
<img width="1113" alt="Bildschirmfoto 2022-05-02 um 16 27 34" src="https://user-images.githubusercontent.com/12912413/166251945-d6b56a2f-fd7b-40d9-80af-2ac8879a557a.png">

**Comment by MattiWe** [comment]
OK, I did a poor job explaining what the issue is. I've updated the issue for clarity. 

On a side note, it would be nice if you could make a new branch for this enhancement and then open a pull request. I try to do this for all enhancements/new features. I try to only push bug fixes directly to master.

**Comment by theelstner** [comment]
i see. thanks for the clarity update on the description.
i have now (in a new local branch) changed the model.py file and added a date to the dataset table in the database like so:

``date = models.CharField(max_length=30, default='2022') ``

added it to the context of the index in the views.py like so:

``context["datasets"] = model.get_datasets()``

now i have two questions:

1)how do i call a specific dataset for a specific task to access its date variable in the index html, so sth like: 
``{{ datasets[task_id].date }}``
(i know this would not work or do i have direct access like this?)
2)how do i fill the date variable in the database?

**Comment by MattiWe** [comment]
You could try to follow the other fields from the model to the website. I think the 'default_upload_name' field works quite similarly.

**Comment by MattiWe** [comment]
merged into dev
