### ISSUE TITLE
It seems like the evaluator runs in the background after some time?

### ISSUE THREAD

**Issue by mam10eks** [tira-io/tira#234]
**Current behavior**
When I run an evaluator in the frontend, the frontend first shows that the evaluator is running, and after maybe 10 or 20 seconds the page reloads which indicates to me that the evaluation is finished.

But the evaluator result is not displayed in the frontend.
After reloading the page a few times, I see the evaluator results.

**Expected behavior**
The frontend should indicate that the evaluator is running until the results of the evaluator are available (otherwise I think something failed, and restart the evaluator, which then gave me some error messages like transaction already running).

**Comment by mam10eks** [comment]
Maybe this is a good issue for @Dumpling97? (cc. @MattiWe)

**Comment by MattiWe** [comment]
The thing is, this already happens. 
The frontend only reloads after the results are retrieved, parsed, and loaded into the database. Then it still waits a few seconds. 

I have no clue why the additional reload is necessary. I wanted to fix this while reworking the Software page with VUE, because there I can solve it without reloading the page. But for this I want to wait for Bastian to finish the webpack build.

**Comment by MattiWe** [comment]
I go by the time where the hosts confirm that the evaluation has finished.
