### ISSUE TITLE
Usability Enhancement

### ISSUE THREAD

**Issue by mam10eks** [tira-io/tira#274]
Clicking on a disabled button should hint to a user that it did not start the software.
For instance, it happened now multiple times to me that I thought the software should be running, but the button was only disabled. (because I forgot to select the dataset)

![Screenshot_20220924_103818](https://user-images.githubusercontent.com/10050886/192088992-75ea0f49-7be2-41a7-8a33-355863a10530.png)

A modal or a red error message would be enough here. I think we had such mechanisms before, and we should use the same mechanism do indicate that the user forgot to fill out some fields.

**Comment by BastianGrahm** [comment]
This was actually a tricky one but is fixed by https://github.com/tira-io/tira/commit/2723323839623639bf7e8516b360f692d3689c9e.
There was a problem where we used to check if the container was valid with a method that as its first action set the error message to `''`. We use this method to style the button as disabled, which means Vue will constantly test with this method if the container is valid now and the button can be shown as enabled. So naturally it constantly sets the form error message to `''` and we can never change it.
I don't see any reason why the method should be setting this string so it should be fine to just remove that line and solve the issue.
