### ISSUE TITLE
Software run lists improvements

### ISSUE THREAD

**Issue by kaaage** [tira-io/tira#346]
1. Do not show evaluation runs in the list
2. For runs that have one or more evaluation runs show `evaluation` button, which open popup for the most recent evaluation run
3. Show the `evaluate` button only for administrator
4. Rename `review` button to `inspect`

**Comment by mam10eks** [comment]
Dear @kaaage,

thanks for implementing this, it works quite well.
I think we discussed, that the evaluate button should also be shown in case there is no evaluation, so also for non-organizer-users.

We otherwise get this problem:

![Screenshot_20221217_081551](https://user-images.githubusercontent.com/10050886/208230651-9ff32a5d-5463-444b-ac81-d4eb2b08f15b.png)


(but of course, it is already a major improvement this way, thank you, the thing described here is more of an minor thing that we can improve)

**Comment by mam10eks** [comment]
This is already implemented now.
