### ISSUE TITLE
Leaderboard showing wrong numbers

### ISSUE THREAD

**Issue by johanneskiesel** [tira-io/tira#347]
**Current behavior**

The leaderboard for ARGUMENTS-VALIDATION on https://www.tira.io/task/valueeval-at-semeval-2023-human-value-detection for "augustine-of-hippo" shows wrong numbers:

![image](https://user-images.githubusercontent.com/187193/207731007-2f8519d9-5094-4162-a142-34c309b830a5.png)

But when I download the RESULT at the end of the table, it contains the right numbers:

![image](https://user-images.githubusercontent.com/187193/207731140-29702e1d-9f0a-4ca5-8cdd-f227fcda8a2e.png)

**Expected behavior**

The numbers in the leaderboard should be the ones in the RESULT

**Comment by johanneskiesel** [comment]
The issue still persists. I do not know what could be the cause, but the numbers displayed are for a run on a different dataset.

- SHOULD BE: arguments-validation-20221205-training/2022-12-13-09-29-45
- BUT IS: arguments-validation-zhihu-20221205-training/2022-12-13-00-26-10

**Comment by mam10eks** [comment]
I was thinking a bit about the issue, and I think the reason is this issue https://github.com/tira-io/tira/issues/319.

The reason is, that the IDs in TIRA were timestamps, i.e.,  `2023-01-07-17-34-35` that must be unique within a user.
But when many software are evaluated in parallel, some might get the same timestamp (as noted in https://github.com/tira-io/tira/issues/319).

The commit above should solve this.
The Ids of an evaluation are now `<OLD-Evaluation-ID>-evaluted-on-<RUN-Id>`, e.g., `2023-01-07-21-53-23-evaluated-run-2023-01-07-21-50-13`.
This should solve the problem, and I test it by running many software in parallel for the same user.

Right now, it looks promising, and I will report back.

**Comment by mam10eks** [comment]
(this also means that we should delete all evaluations and run them again.)

**Comment by mam10eks** [comment]
I just tested it successfully with 10 jobs in parallel for the same user, and we had no collisions of ID's (which is not possible anymore, because of the new schema of the evaluator ids, just wanted to double-check that everything worked):

![Screenshot_20230108_081002](https://user-images.githubusercontent.com/10050886/211185448-16642f3e-6eb0-411b-839b-4544c884f91f.png)

Now I have a final test running with 20 jobs in parallel for the same user, will report as soon as they are finished:

![Screenshot_20230108_083121](https://user-images.githubusercontent.com/10050886/211185468-9a820834-79ab-438f-b260-f405cd1cc7f0.png)

**Comment by mam10eks** [comment]
All jobs from above were successfull, so the underlying problem is resolved.

What we still need to do here is evaluate all runs again, we can do this via the rest API of TIRA.

**Comment by johanneskiesel** [comment]
This now happened again (at least once).

https://www.tira.io/task/valueeval-at-semeval-2023-human-value-detection

Dataset: arguments-test-nahjalbalagha
The Leaderboard shows: augustine-of-hippo, 2023-01-13-12-54-31, 0.574
But the downloaded evaluation shows the real score of 0.182

Even worse, the API download also got me the wrong score, so the tables I send to the participants are all flawed.

**Comment by mam10eks** [comment]
This is now solved (in private chat, some weeks ago. The solution above solved the problem, but I forgot to roll it out to the shared task repository of value-eval. We fixed the problems then manually.)
