### ISSUE TITLE
TIRA can not handle GB-sized datasets

### ISSUE THREAD

**Issue by johanneskiesel** [tira-io/tira#399]
**Current behavior**

When I run a docker submission or upload a run file for a dataset that is a few GB large, prepare-tira-environment times out after one hour as it tries to copy the data in the input directory somewhere else.

**Expected behavior**

Maybe that the input directory is just mounted?

**Severity**

This issue is totally blocking reproducible evaluation for Touche task 3 (image retrieval). If it persists, I will have to disallow Docker submissions for the task unless there is a workaround.

I stripped down the dataset of the large parts that I assume most participants will not use (web archives, page screenshots, but also the HTML code and the file that contains element locations and CSS information!). The dataset is now only 8 GB. But that is still too much to finish copying in 1 hour.

**Comment by johanneskiesel** [comment]
Any news on this? This issue is currently blocking project completion for the IR groups in Jena and one group in Weimar.

**Comment by mam10eks** [comment]
Dear Johannes,

I am really sorry for the delay.
I started to look into this last Saturday, but then I saw some other blocking issue that prevented my initial solution, but today I was able to resolve the previous blocking issue, and I just made a first test, and the solution works now for the dataset above.

(the problem seems to be not really the size, as I used datasets of similar size before, but rather that the directory contains many small files, e.g., I currently copy some data from that directory in our cephfs with approximately 10 to 20 MB per minute.)

As my initial tests with the solution for this were successful, I will now deploy it in the full system.

**Comment by mam10eks** [comment]
Perfect, everything works pretty well.

I executed my tests several times on a duplicate dataset to which I applied the solution. It worked perfectly, so we can apply it to the "real" dataset as well.

In the best case, we can shortly discuss this shortly?
Than we can apply it directly to the real dataset, and then we can close the issue.

**Comment by mam10eks** [comment]
This was solved via mounts in the kubernetes pods that execute the submissions.
