### ISSUE TITLE
Version 0 of running processes in Vuetify

### ISSUE THREAD

**Issue by mam10eks** [tira-io/tira#434]

**Comment by mam10eks** [comment]
At the moment, the overview of running processes is realized as this (in this example, 2 jobs are running, 1 is expanded, might make sense just to use a expandable table again?):

![Screenshot_20230523_152051](https://github.com/tira-io/tira/assets/10050886/c28a0b82-a60e-4e39-9307-0d6707903611)

**Comment by potthast** [comment]
Thank you!

Quick feedback:
- Grey panel has different font sizes, some small fonts, some larger fonts.
- The listing on the right looks a gibt close to the inputs, but keys and values far from each other.
- Can't the image and the command also just be part of the right listing? 
- The bottom row with the refresh information is a bit out of alignment horizontally.
- Since the outer panels are in principle a table with five columns, shouldn't there be a header with a title for each column?

**Comment by mam10eks** [comment]
This is implemented now.
